# Generated by Django 5.1.7 on 2025-03-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junction_id', models.CharField(max_length=100, unique=True)),
                ('number_of_vehicles', models.IntegerField()),
            ],
        ),
    ]
